mock session manager
Xcov19/android-mycovidconnect pull request #17
Opened 2020-09-20 19:58 UTC by AmosKorir

Mock Session manager

2020-09-22 05:30 UTC, jumaallan approved these changes

2020-09-22 14:49 UTC, maplonki approved these changes

2020-09-22 21:00 UTC, jumaallan commented
@AmosKorir 

We can use the shared pref file I setup, and make it an observable using LiveData

2020-09-22 21:44 UTC, AmosKorir commented
@jumaallan That is fine.

2020-09-23 07:07 UTC, codecakes commented
@AmosKorir @jumaallan canu guys merge it if its done?

2020-09-23 08:41 UTC, codecakes reviewed
Use smart commits if you are working on a jira user story: https://support.atlassian.com/bitbucket-cloud/docs/use-smart-commits/

2020-09-23 08:41 UTC, codecakes requested changes

2020-09-23 08:41 UTC, codecakes commented on app/src/main/java/com/ht117/yukute/sessionmanager/SessionManagerInterface.kt
> +}
empty line EOF in all files

2020-09-27 09:22 UTC, codecakes commented
any updates guys?

2020-09-28 09:12 UTC, merged