Feat/myc 55 - Search functionality
Xcov19/android-mycovidconnect pull request #19
Opened 2020-09-23 00:19 UTC by maplonki

This adds the location request portion of the search and displays the user location on the map. 

Will update once the backend portion is finished

2020-09-23 07:10 UTC, codecakes commented on .gitignore
> +.idea/codeStyles/codeStyleConfig.xml
can we not do just `.idea/` ?

2020-09-23 07:13 UTC, jumaallan commented on .gitignore
> +.idea/codeStyles/codeStyleConfig.xml
+1 on this

2020-09-23 17:22 UTC, jumaallan approved these changes

2020-09-23 19:47 UTC, codecakes commented
@jumaallan @maplonki fastlane android test CI is breaking;

2020-09-23 19:49 UTC, jumaallan commented
I noticed

Issue is the key.properties file 

@maplonki - you can pass the config via Fastlane. Let me know if you can set that up

2020-09-23 19:50 UTC, codecakes approved these changes
We should have a precommit hook that ktlints automatically:
https://medium.com/binar-academy/android-kotlin-code-quality-check-using-detekt-and-git-hooks-pre-push-mac-and-linux-556c111bc71b

2020-09-23 23:47 UTC, maplonki commented
> I noticed
> 
> Issue is the key.properties file
> 
> @maplonki - you can pass the config via Fastlane. Let me know if you can set that up

@jumaallan can you help out with that?

2020-09-24 13:01 UTC, codecakes commented
> > I noticed
> > Issue is the key.properties file
> > @maplonki - you can pass the config via Fastlane. Let me know if you can set that up
> 
> @jumaallan can you help out with that?

@jumaallan you can push this commit

2020-09-27 09:22 UTC, codecakes commented
any updates here?

2020-09-28 06:20 UTC, jumaallan commented
> any updates here?

Let me fix that today

2020-09-28 09:03 UTC, jumaallan commented
> > any updates here?
> 
> Let me fix that today

@codecakes @maplonki 

I've replaced the implementation that reads from keys.properties file, and replaced with one that reads from gradle.properties - this can be done in two ways:

1. on the local gradle.properties 
2. on the global gradle.properties

I'll document on the README, how to do that. 

I have also updated Fastlane to read the Maps API Key, from Github Secrets when doing a build - @codecakes - Kindly create a secret with the name MAPS_DEBUG_KEY, and paste the debug API Key - builds should now work with that

2020-09-28 09:08 UTC, codecakes commented
> > > any updates here?
> > 
> > 
> > Let me fix that today
> 
> @codecakes @maplonki
> 
> I've replaced the implementation that reads from keys.properties file, and replaced with one that reads from gradle.properties - this can be done in two ways:
> 
>     1. on the local gradle.properties
> 
>     2. on the global gradle.properties
> 
> 
> I'll document on the README, how to do that.
> 
> I have also updated Fastlane to read the Maps API Key, from Github Secrets when doing a build - @codecakes - Kindly create a secret with the name MAPS_DEBUG_KEY, and paste the debug API Key - builds should now work with that

Thanks @jumaallan ; could you ping me our group the api key?

2020-09-28 09:09 UTC, codecakes requested changes
@jumaallan is the linter used in the ide adding blank line EOF?

2020-09-28 09:11 UTC, jumaallan commented
> > > > any updates here?
> > > 
> > > 
> > > Let me fix that today
> > 
> > 
> > @codecakes @maplonki
> > I've replaced the implementation that reads from keys.properties file, and replaced with one that reads from gradle.properties - this can be done in two ways:
> > ```
> > 1. on the local gradle.properties
> > 
> > 2. on the global gradle.properties
> > ```
> > 
> > 
> > I'll document on the README, how to do that.
> > I have also updated Fastlane to read the Maps API Key, from Github Secrets when doing a build - @codecakes - Kindly create a secret with the name MAPS_DEBUG_KEY, and paste the debug API Key - builds should now work with that
> 
> Thanks @jumaallan ; could you ping me our group the api key?

I don't have the API Key, probably @maplonki has the keys

2020-09-28 09:13 UTC, jumaallan commented
> @jumaallan is the linter used in the ide adding blank line EOF?

I don't think so - I will setup the following:
1. https://github.com/JLLeitschuh/ktlint-gradle
2. https://github.com/detekt/detekt
3. https://github.com/diffplug/spotless

I'll do a separate PR for that

2020-09-28 09:14 UTC, codecakes commented
> > @jumaallan is the linter used in the ide adding blank line EOF?
> 
> I don't think so - I will setup the following:
> 
>     1. https://github.com/JLLeitschuh/ktlint-gradle
> 
>     2. https://github.com/detekt/detekt
> 
>     3. https://github.com/diffplug/spotless
> 
> 
> I'll do a separate PR for that

thanks alot!@

2020-09-28 09:34 UTC, jumaallan commented
Added some TODOs, and dummy code to kill the linter warnings - FYI

@maplonki @codecakes 

We need to merge all PRs to develop, and rework from there

2020-09-28 09:35 UTC, jumaallan commented
![image](https://user-images.githubusercontent.com/25085146/94416079-0de11680-0187-11eb-9ae4-fd26dd431707.png)

@maplonki can you merge this? or @codecakes  - I am not able to merge the PR

2020-09-28 10:25 UTC, codecakes approved these changes
Use smart commits if working on a JIRA user ticket: https://support.atlassian.com/bitbucket-cloud/docs/use-smart-commits/

2020-09-28 10:26 UTC, merged